package devtoclient

import (
	"fmt"
	"time"
)

type Post struct {
	TypeOf                 string      `json:"type_of"`
	ID                     int         `json:"id"`
	Title                  string      `json:"title"`
	Description            string      `json:"description"`
	ReadablePublishDate    string      `json:"readable_publish_date"`
	Slug                   string      `json:"slug"`
	Path                   string      `json:"path"`
	URL                    string      `json:"url"`
	CommentsCount          int         `json:"comments_count"`
	PositiveReactionsCount int         `json:"positive_reactions_count"`
	CollectionID           interface{} `json:"collection_id"`
	PublishedTimestamp     time.Time   `json:"published_timestamp"`
	CoverImage             string      `json:"cover_image"`
	SocialImage            string      `json:"social_image"`
	CanonicalURL           string      `json:"canonical_url"`
	CreatedAt              time.Time   `json:"created_at"`
	EditedAt               interface{} `json:"edited_at"`
	CrosspostedAt          interface{} `json:"crossposted_at"`
	PublishedAt            time.Time   `json:"published_at"`
	LastCommentAt          time.Time   `json:"last_comment_at"`
	TagList                []string    `json:"tag_list"`
	Tags                   string      `json:"tags"`
	User                   struct {
		Name            string      `json:"name"`
		Username        string      `json:"username"`
		TwitterUsername string      `json:"twitter_username"`
		GithubUsername  string      `json:"github_username"`
		WebsiteURL      interface{} `json:"website_url"`
		ProfileImage    string      `json:"profile_image"`
		ProfileImage90  string      `json:"profile_image_90"`
	} `json:"user"`
}

type Payload struct {
	Article Article `json:"article"`
}
type Article struct {
	Title        string   `json:"title"`
	BodyMarkdown string   `json:"body_markdown"`
	Published    bool     `json:"published"`
	Tags         []string `json:"tags"`
}

func (c *Client) GetArticles() ([]Post, error) {
	var posts []Post
	url := fmt.Sprintf("/articles")
	_, err := c.Request("GET", url, nil, &posts)
	return posts, err
}

func (c *Client) GetArticle(postID int) (Post, error) {
	var post Post
	url := fmt.Sprintf("/articles/%d", postID)
	_, err := c.Request("GET", url, nil, &post)
	return post, err
}

func (c *Client) AddArticle(newPost Article) (Post, error) {
	var savedPost Post
	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go
	data := Payload{
		Article: newPost,
	}
	_, err := c.Request("POST", "/articles", data, &savedPost)
	return savedPost, err
}
